# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

    config.vm.define :saml do |saml|
         # Every Vagrant virtual environment requires a box to build off of.
         saml.vm.box = "fillup/centos-6.5-x86_64-minimal"

         # Create a private network, which allows host-only access to the machine
         # using a specific IP.
         saml.vm.network "private_network", ip: "192.168.55.10"

         # Share an additional folder to the guest VM. The first argument is
         # the path on the host to the actual folder. The second argument is
         # the path on the guest to mount the folder. And the optional third
         # argument is a set of non-required options.
         saml.vm.synced_folder "../simplesamlphp/", "/var/www/simplesamlphp"

         # Provisioning script
         saml.vm.provision :shell, :path => "provision-saml.sh"
    end

    config.vm.define :oauth do |oauth|
        # Every Vagrant virtual environment requires a box to build off of.
        oauth.vm.box = "fillup/centos-6.5-x86_64-minimal"

        # Create a private network, which allows host-only access to the machine
        # using a specific IP.
        oauth.vm.network "private_network", ip: "192.168.55.11"

        # Share an additional folder to the guest VM. The first argument is
        # the path on the host to the actual folder. The second argument is
        # the path on the guest to mount the folder. And the optional third
        # argument is a set of non-required options.
        oauth.vm.synced_folder "../php-oauth/", "/var/www/simpleoauthphp"

        # Provisioning script
        oauth.vm.provision :shell, :path => "provision-oauth.sh"
    end

end
